language: python
python:
  - "3.5"

#command to install dependencies
install:
  - sudo apt-get install ffmpeg
  - "pip install -r requirements.txt"
  - pip install numpydoc

#command to run tests
script: nosetests --exe --with-coverage --cover-package=music_feats

#command to build sphinx documentations
#script: sphinx-build -nW -b html -c ./config -d _build/doctrees . _build/html
script: python -m sphinx -n -b html -c ./config -d _build/doctrees . _build/html

sudo: required
