language: python
python:
  - "3.5"

#command to install dependencies
install:
  - sudo apt-get install ffmpeg
  - "pip install -r requirements.txt"

#command to run tests
script: nosetests --exe --with-coverage --cover-package=music_feats

#command to build sphinx documentations
before_script: cd config
script: sphinx-build -b html -d _build/doctrees   . _build/html

sudo: required
